### ISSUE TITLE
Problem with running of the app locally in dev mode

### ISSUE THREAD

**Issue by olegakbarov** [thegeez/clj-board#1]
First of all — thanks for cool example! Code looks really nice but i have trouble running it locally.

My steps were following:
1. Clone repo
2. `lein repl`
3. `=> (all)`

At this point i had this Exception: 

```
Failed to compile "resources/public/js/app.js" in 0.735 seconds.
----  Exception    ----

  java.io.IOException : Cannot run program "notify-send": error=2, No such file or directory
  java.io.IOException : error=2, No such file or directory

----  Exception Stack Trace  ----
```

Could you please give me hint what could be possibly wrong with my setup?

**Comment by thegeez** [comment]
That's fixed here:
https://github.com/thegeez/clj-board/commit/0eaac8cc547de24734ffd112ef67f3a448523625

notify-send does toaster pop-up notifications. That program is probably not on every system and is not needed because Figwheel shows notifications in the browser by itself.

**Comment by olegakbarov** [comment]
That worked, thanks!
